name: CodeCov

on:
  push:
    branches:
      - master

jobs:
  codecov:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
        fetch-depth: 0
    - name: Set up Git
      run: |
        git config pull.rebase true
        git config --global user.name "Test User"
        git config --global user.email "test@example.com"
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
        pip install -r ./requirements_dev.txt
    - name: Generate coverage report
      run: pytest --cov=./ --cov-report=xml
    - name: Upload coverage report to CodeCov
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${{ secrets.CODECOV_TOKEN }} -f coverage.xml -Z
