name: Test Submit URLs Action

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  test-submit-urls-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get branch name whether it's a pull request or the master branch
        run: |
          if [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
            REF_NAME="${GITHUB_HEAD_REF}"
          else
            REF_NAME="${GITHUB_REF_NAME}"
          fi
      - name: Submit single URL to IndexNow
        run: >
          python jakob-bagterp/index-now-submit-sitemap-urls-action/$REF_NAME/src/helper/submit.py
          jakob-bagterp.github.io
          6d71a14ac15c4c41a0c19e641f659208
          https://jakob-bagterp.github.io/index-now-api-key.txt
          yandex
          --sitemap-locations https://jakob-bagterp.github.io/index-now-submit-sitemap-urls-action/sitemap.xml
      - name: Submit multiple URLs to IndexNow
        run: >
          python jakob-bagterp/index-now-submit-sitemap-urls-action/$REF_NAME/src/helper/submit.py
          jakob-bagterp.github.io
          6d71a14ac15c4c41a0c19e641f659208
          https://jakob-bagterp.github.io/index-now-api-key.txt
          yandex
          --sitemap-locations "
            https://jakob-bagterp.github.io/sitemap.xml,
            https://jakob-bagterp.github.io/index-now-submit-sitemap-urls-action/sitemap.xml"
