name: Test

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
        pip install -r ./requirements_dev.txt
        pip install .
    - name: Run linting tests with flake8
      run: flake8 src test --max-line-length=120 --extend-ignore=E501
    - name: Run tests with pytest
      run: pytest
    - name: Run tests with mypy
      run: mypy src --ignore-missing-imports --follow-imports=skip --strict
