name: Test Submit URLs Action

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - master

permissions: read-all

jobs:
  test-submit-urls-action:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Submit single URL to IndexNow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh workflow run test_submit_urls_action.yml --ref ${{ github.ref_name }}
          -f host=jakob-bagterp.github.io
          -f api_key=6d71a14ac15c4c41a0c19e641f659208
          -f api_key_location=https://jakob-bagterp.github.io/index-now-api-key.txt
          -f urls="https://jakob-bagterp.github.io/index-now-submit-sitemap-urls-action/"
          -f endpoint=yandex
      - name: Submit multiple URLs to IndexNow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh workflow run test_submit_urls_action.yml --ref ${{ github.ref_name }}
          -f host=jakob-bagterp.github.io
          -f api_key=6d71a14ac15c4c41a0c19e641f659208
          -f api_key_location=https://jakob-bagterp.github.io/index-now-api-key.txt
          -f urls="
            https://jakob-bagterp.github.io,
            https://jakob-bagterp.github.io/index-now-submit-sitemap-urls-action/"
          -f endpoint=yandex
